### ISSUE TITLE
Error when a rectangle selected

### ISSUE THREAD

**Issue by schaemar** [lcoandrade/OSMDownloader#1]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/martin/.qgis2/python/plugins/OSMDownloader/rectangleAreaTool.py", line 57, in canvasReleaseEvent
    self.transformCoordinates()
  File "/home/martin/.qgis2/python/plugins/OSMDownloader/rectangleAreaTool.py", line 88, in transformCoordinates
    epsg = self.canvas.mapSettings().destinationCrs().authid()
AttributeError: 'QgsMapCanvas' object has no attribute 'mapSettings'

Python version:
2.7.6 (default, Oct 26 2016, 20:33:43) 
[GCC 4.8.4]

QGIS version:
2.0.1-Dufour Dufour, exported

**Comment by lcoandrade** [comment]
I made a port to QGIS 3. I suggest you to use the new version. The QGIS 2 version is no longer supported.

Please try again and tell me if you find this error again.
