### ISSUE TITLE
Replace 'imp' for python > 3.12 

### ISSUE THREAD

**Issue by Marwe** [lcoandrade/OSMDownloader#20]
From python 3.12 on the dependency `imp` was finally [removed](https://docs.python.org/3/library/imp.html):

```
Couldn't load plugin 'OSMDownloader' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'imp' 
```

Migration to [importlib](https://docs.python.org/3.11/library/importlib.html#module-importlib) is suggested with some details in the [notice](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-removed-imp).

Just for completeness my current versions:
Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] 
QGIS version: 3.34.13-Prizren Prizren, 222b59952c9

**Comment by Marwe** [comment]
Looking into the source code I cannot find a reference there, it might be an issue with the system python packages - the error is finally triggered from future package. Full stacktrace is:

```
ModuleNotFoundError: No module named 'imp' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/QGIS/QGIS3/profiles/dev/python/plugins/OSMDownloader/__init__.py", line 34, in classFactory
    from .osmDownloader import OSMDownloader
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/QGIS/QGIS3/profiles/dev/python/plugins/OSMDownloader/osmDownloader.py", line 31, in 
    from .osmDownloader_dialog import OSMDownloaderDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/QGIS/QGIS3/profiles/dev/python/plugins/OSMDownloader/osmDownloader_dialog.py", line 36, in 
    from .osm_downloader import OSMRequest
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/share/QGIS/QGIS3/profiles/dev/python/plugins/OSMDownloader/osm_downloader.py", line 25, in 
    from future import standard_library
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/future/standard_library/__init__.py", line 65, in 
    import imp
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'


Python-Version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] 
QGIS-Version: 3.34.13-Prizren Prizren, 222b59952c9 
```

Package: python3-future Version: 0.18.2-6ubuntu2

**Comment by Marwe** [comment]
Since this is an identified [Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/python-future/+bug/2071640), this can be closed.

**Comment by Marwe** [comment]
Since this is an identified [Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/python-future/+bug/2071640), this can be closed.
