### ISSUE TITLE
ModuleNotFoundError: No module named 'future' 

### ISSUE THREAD

**Issue by phoneee** [lcoandrade/OSMDownloader#7]
Couldn't load plugin 'OSMDownloader' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/__init__.py", line 34, in classFactory
    from .osmDownloader import OSMDownloader
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osmDownloader.py", line 31, in 
    from .osmDownloader_dialog import OSMDownloaderDialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osmDownloader_dialog.py", line 36, in 
    from .osm_downloader import OSMRequest
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osm_downloader.py", line 25, in 
    from future import standard_library
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.2-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/phoneee/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by lcoandrade** [comment]
As the plugin was ported it is necessary to use the future library because it is a compatibility layer between Python 2 and Python 3. I recommend you to install future using: pip3 install future
